<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('grader_php')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_grader_php.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('grader_php.so')) return;
    } else {
      if (!dl('grader_php.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class grader_php {
	static function submit_new_task($sourceName,$sourceCont,$test) {
		return submit_new_task($sourceName,$sourceCont,$test);
	}

	static function get_task_status($taskId) {
		return get_task_status($taskId);
	}

	static function destroy_task($taskId) {
		destroy_task($taskId);
	}
}

/* PHP Proxy Classes */

?>
