/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_GRADER_PHP_H
#define PHP_GRADER_PHP_H

extern zend_module_entry grader_php_module_entry;
#define phpext_grader_php_ptr &grader_php_module_entry

#ifdef PHP_WIN32
# define PHP_GRADER_PHP_API __declspec(dllexport)
#else
# define PHP_GRADER_PHP_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(grader_php);
PHP_MSHUTDOWN_FUNCTION(grader_php);
PHP_RINIT_FUNCTION(grader_php);
PHP_RSHUTDOWN_FUNCTION(grader_php);
PHP_MINFO_FUNCTION(grader_php);

ZEND_NAMED_FUNCTION(_wrap_submit_new_task);
ZEND_NAMED_FUNCTION(_wrap_get_task_status);
ZEND_NAMED_FUNCTION(_wrap_destroy_task);
#endif /* PHP_GRADER_PHP_H */
